# Generated by Django 6.0.1 on 2026-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_setup', 'Can view Setup section')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
