# Generated by Django 6.0.1 on 2026-01-20 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'default_permissions': (), 'managed': False, 'permissions': [('approve_setup', 'Can approve Setup section')]},
        ),
    ]
