# Generated by Django 6.0.1 on 2026-01-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_alter_setup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setup',
            options={'managed': False, 'permissions': [('approve_setup', 'Can approve Setup section')]},
        ),
    ]
