# Generated by Django 6.0.1 on 2026-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_demo', 'Can view Demo section')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
