# Generated by Django 6.0.1 on 2026-01-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_demo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'managed': False, 'permissions': [('approve_demo', 'Can approve Demo section')]},
        ),
    ]
