# Generated by Django 6.0.1 on 2026-01-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_alter_hub_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hub',
            options={'managed': False, 'permissions': [('approve_hub', 'Can approve Hub section')]},
        ),
    ]
